### ISSUE TITLE
Add CI pipeline

### ISSUE THREAD

**Issue by schornakj** [ros-industrial-consortium/tesseract_ros2#12]
[`tesseract_ros`](https://github.com/ros-industrial-consortium/tesseract_ros/blob/master/.travis.yml) has a working Travis CI pipeline, so it would be really good if we had one here too.

**Comment by mpowelson** [comment]
I suppose you could use this docker file. We are using it in the [CRS](https://github.com/swri-robotics/collaborative-robotic-sanding/blob/master/.travis.yml) repo. It has QT5.12 for ROSSCXML, but it would work until somone takes the time to make one specifically without it. It has all of the stuff for Tesseract already.

mpowelson/bionic-qt-ros:eloquent

**Comment by mpowelson** [comment]
Addressed in #19
